export enum BorrowerVerificationFlags {
  PHONE_NUMBER = "PHONE_NUMBER",
  EMAIL = "EMAIL",
  DEPOSIT = "DEPOSIT",
  MEMBERSHIP_FEE_PAID = "MEMBERSHIP_FEE_PAID",
  EXISTING_MEMBERS_VOUCH = "EXISTING_MEMBERS_VOUCH",
}
