export enum ThingStatus {
  READY = "READY",
  WAITING_FOR_LENDER_APPROVAL_TO_BORROW = "WAITING_FOR_LENDER_APPROVAL_TO_BORROW",
  BORROWED = "BORROWED",
  DAMAGED = "DAMAGED",
  RESERVED = "RESERVED",
}
